//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmpNum { get; set; }
        public string EmpID { get; set; }
        public string EmpName { get; set; }
        public string DeptID { get; set; }
        public string EmpType { get; set; }
        public string PAN { get; set; }
        public byte[] EmpPassword { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
