//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDTransaction
    {
        public int FDTransNum { get; set; }
        public string FDTransactionID { get; set; }
        public string FDAccountID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string FDType { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual FixedDepositAccount FixedDepositAccount { get; set; }
    }
}
