//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixedDepositAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FixedDepositAccount()
        {
            this.FDTransactions = new HashSet<FDTransaction>();
        }
    
        public int FDNum { get; set; }
        public string FDAccountID { get; set; }
        public string CustomerID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal DepositAmount { get; set; }
        public string Status { get; set; }
        public decimal FDROI { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDTransaction> FDTransactions { get; set; }
    }
}
