//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanTransaction
    {
        public int LoanTransNum { get; set; }
        public string LoanTransactionID { get; set; }
        public string LNAccountID { get; set; }
        public System.DateTime EMIDate_Actual { get; set; }
        public Nullable<System.DateTime> EMIDate_Paid { get; set; }
        public Nullable<decimal> LatePenalty { get; set; }
        public decimal Amount { get; set; }
        public decimal Outstanding { get; set; }
    
        public virtual LoanAccount LoanAccount { get; set; }
    }
}
